//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrayIconForTinkerForge {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal eng() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrayIconForTinkerForge.eng", typeof(eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die you can now establish a connection with your stack! ähnelt.
        /// </summary>
        internal static string _BrickDeamonIsStartedText {
            get {
                return ResourceManager.GetString("_BrickDeamonIsStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the BrickDeamon Service is now RUNNING! ähnelt.
        /// </summary>
        internal static string _BrickDeamonIsStartedTitle {
            get {
                return ResourceManager.GetString("_BrickDeamonIsStartedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die if you want to connect your stack, the service needs to be started! ähnelt.
        /// </summary>
        internal static string _BrickDeamonIsStoppedText {
            get {
                return ResourceManager.GetString("_BrickDeamonIsStoppedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die the BrickDeamon Service is now STOPPED! ähnelt.
        /// </summary>
        internal static string _BrickDeamonIsStoppedTitle {
            get {
                return ResourceManager.GetString("_BrickDeamonIsStoppedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BrickDaemon is currently: ähnelt.
        /// </summary>
        internal static string _BrickStatusDisplay {
            get {
                return ResourceManager.GetString("_BrickStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die detecting... ähnelt.
        /// </summary>
        internal static string _detecting {
            get {
                return ResourceManager.GetString("_detecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not restart the Service due to an error. ähnelt.
        /// </summary>
        internal static string _errorDuringReStartOfService {
            get {
                return ResourceManager.GetString("_errorDuringReStartOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not start the Service due to an error. ähnelt.
        /// </summary>
        internal static string _errorDuringStartOfService {
            get {
                return ResourceManager.GetString("_errorDuringStartOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not stop the Service due to an error. ähnelt.
        /// </summary>
        internal static string _errorDuringStopOfService {
            get {
                return ResourceManager.GetString("_errorDuringStopOfService", resourceCulture);
            }
        }
    }
}
